### ISSUE TITLE
Google Calendar - Left-side Checkboxes

### ISSUE THREAD

**Issue by Obscure2020** [EvHaus/google-redesigned#10]
Hi there. I use your Dark Mode for Google Calendar.

I noticed something different today.
I don't know how long it's been different, but I could have sworn it wasn't like this before.

You know these checkboxes on the left side panel?
![image](https://user-images.githubusercontent.com/69320464/192872113-7919e8dd-be0f-4f53-97c7-415fe6365ecc.png)
I could've sworn these checkboxes used to be individually colored according to the colors I had set for these calendars.

_[REDACTED]_ is purple, my _Work Schedule_ is green, and the checkboxes used to be colored accordingly as well.
Now they're all just `--GRSELECTED`-colored.

**Comment by EvHaus** [comment]
Yup. Looks like Google changed something and it broke the styling. Will fix.

**Comment by Obscure2020** [comment]
Yep! I can confirm it's fixed. Thanks!
![image](https://user-images.githubusercontent.com/69320464/193045752-a2caf0f5-56f9-4771-ad46-a58d710030e3.png)
