### ISSUE TITLE
Custom Recurrence Broken

### ISSUE THREAD

**Issue by Obscure2020** [EvHaus/google-redesigned#11]
Found a new issue with the Google Calendar styling.
The **Custom Recurrence** menu is slightly broken.
In this menu, there is a row of circles with the initials of the days of the week.
When you click on these circles, they are supposed to change color to denote that they are selected.
This coloring is now broken.

Here's without the userstyle:
![Screen Shot 2022-10-17 at 12 31 59](https://user-images.githubusercontent.com/69320464/196233258-fd825d16-c7c6-4588-a4c6-ffbb27bf078f.png)

And here's _with_ the userstyle:
![Screen Shot 2022-10-17 at 12 32 19](https://user-images.githubusercontent.com/69320464/196233382-876946e9-569e-4a44-b547-1d09e042b5e9.png)

I would assume the selected days in the **Repeat on** section should be colored with the accent color.
I also think the radio button in the **Ends** section should be the accent color, rather than blue.

**Comment by EvHaus** [comment]
Thanks for the report. This is fixed in the latest version.
