### ISSUE TITLE
Calendar Event dropdowns are not following theme

### ISSUE THREAD

**Issue by kyle-ds** [EvHaus/google-redesigned#14]
Dropdowns in event edit are White with grey text, hard to see

![image](https://user-images.githubusercontent.com/51097593/214511954-3c108a62-e98f-4271-a881-df0de863e586.png)

**Comment by kyle-ds** [comment]
Class names on inspection for text dropdowns show "MocG8c LMgvRb KKjvXb"

Not sure how to read the colour selector classes

**Comment by EvHaus** [comment]
Thanks for the report. This should be fixed in the latest 20230126.0.0 version
