### ISSUE TITLE
Invisible Text

### ISSUE THREAD

**Issue by livejamie** [EvHaus/google-redesigned#2]
Love this userstyle

When creating an event in the Google Calendar Iframe the text is invisible

![image](https://user-images.githubusercontent.com/49513/134417162-66d6e814-609f-45d5-b009-43c853e53340.png)

![image](https://user-images.githubusercontent.com/49513/134417254-0f84daa7-fb2c-4277-abe4-34538a9347df.png)

The top of the frame also appears unstyled

Thanks!

**Comment by EvHaus** [comment]
This is in the Google Calendar sidebar that appears in Gmail, right? The userstyle doesn't support any of those apps right now.

**Comment by livejamie** [comment]
Yeah since it's an iframe of the google calendar site stylus tries to use it.

It's a bummer it's nearly perfect except for this one bit. Thanks anyways.

If you have any spare time and wanted to get it fixed I'd be happy to make a donation in your name to your favorite charity, lmk.

**Comment by EvHaus** [comment]
Just added support for this. If you hit the "Check styles for updates" button in your Stylus plugin, it should be nicely handled now.
