### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by FrostyNick** [EvHaus/google-redesigned#3]
World clock and week numbers aren't supported.

To see those options, enable the following:
`Settings >> World clock >> Show world clock` (low contrast)
`Settings >> View options >> Show week numbers` (white background)

![image](https://user-images.githubusercontent.com/57016218/140088183-64189f22-abc7-47fd-b94f-c120a0239416.png)
![image](https://user-images.githubusercontent.com/57016218/140088399-298c09f3-caef-4b13-b2bc-ae7e0ee4c2cc.png)

But otherwise well done style. I like it.

**Comment by EvHaus** [comment]
Thanks for the bug report. This has been fixed in the latest version. Please try again after updating.

**Comment by EvHaus** [comment]
@FrostyNick Thanks so much for your sponsorship! It really means a lot.

**Comment by FrostyNick** [comment]
@EvHaus No problem! Glad to sponsor you. 🙂
