### ISSUE TITLE
[Calendar] Color of some texts are no longer modified

### ISSUE THREAD

**Issue by AvgZing** [EvHaus/google-redesigned#34]
![image](https://github.com/EvHaus/google-redesigned/assets/25853984/c68b316d-cf6e-4c4a-840f-00188b4341e6)
It's challenging to see text in some of these cases. The calendar on the left is also now broken.
![image](https://github.com/EvHaus/google-redesigned/assets/25853984/aa16edc4-e332-4e7a-b179-3e07f8f5e6f4)
Google has been changing everything lately and it is frustrating, so I feel your pain.

**Comment by EvHaus** [comment]
I can reproduce. Will fix when I get a chance.

**Comment by EvHaus** [comment]
Fixed in the latest version.
