### ISSUE TITLE
[Google Calendar] Calendar view no longer modified

### ISSUE THREAD

**Issue by eitchtee** [EvHaus/google-redesigned#42]
As of today, calendar view on google calendar is no longer modified by this style.

![image](https://github.com/EvHaus/google-redesigned/assets/10510126/05c080b6-9537-47e4-b36f-00d6230de5d2)

Everything else, including other views seems to be fine.

**Comment by EvHaus** [comment]
Thanks for the report. Fixed in the latest version!
