### ISSUE TITLE
Google Calendar Redesign: White Lines and Bar

### ISSUE THREAD

**Issue by AvgZing** [EvHaus/google-redesigned#44]
Redesign seems to be still rolling out, my work account had it yesterday and personal has it now.

Seems to be div .ouBNcf, .iHNmdb for the sidebar and not sure about the lines.

![image](https://github.com/EvHaus/google-redesigned/assets/25853984/78b8c1f1-3a34-4079-a194-c380ccb64770)

**Comment by EvHaus** [comment]
Thanks for the report. Fixed in the latest version.

**Comment by AvgZing** [comment]
Thank you! So clean that I forgot this was broken until checking my notifications here. Great work :)
