### ISSUE TITLE
Colors in year view are displayed incorrectly

### ISSUE THREAD

**Issue by pityalvarez** [EvHaus/google-redesigned#5]
![image](https://user-images.githubusercontent.com/97750378/155040109-ee75c61c-0b9e-446f-a494-cda42e099678.png)
![image](https://user-images.githubusercontent.com/97750378/155040119-a307fa81-88d9-4d28-a060-9e3571656b6e.png)

**Comment by EvHaus** [comment]
Good suggestion! Pushed a new update which makes the colors more prominent.
