### ISSUE TITLE
Context menu text now appears as black over black

### ISSUE THREAD

**Issue by NicolasWebDev** [EvHaus/google-redesigned#54]
Hi,

Since this week, there is this problem when clicking on the context menu of a particular event:
![Screenshot from 2024-04-22 09-02-23](https://github.com/EvHaus/google-redesigned/assets/2276631/59185b11-1148-4869-be93-94164abbd117)

Thanks for the great work!

**Comment by EvHaus** [comment]
Thanks. Fixed in the latest version.
