### ISSUE TITLE
The title of the "Cancellation email" popup is too dark to see

### ISSUE THREAD

**Issue by NicolasWebDev** [EvHaus/google-redesigned#58]
Hi,

Since this week, the title of the Cancellation email popup appears as black over black.

Screenshot
![Screenshot from 2024-05-20 13-36-59](https://github.com/EvHaus/google-redesigned/assets/2276631/a68bc5a3-dfa7-4898-ba67-3070f56d023f)

Screenshot with the text selected
![Screenshot from 2024-05-20 13-37-04](https://github.com/EvHaus/google-redesigned/assets/2276631/5cab99dd-1d60-4a89-acc6-820685bd7954)

Thanks for the great work!

**Comment by EvHaus** [comment]
Thanks! Fixed in the latest release.

**Comment by NicolasWebDev** [comment]
Thanks for the quick fix, as always!
