### ISSUE TITLE
New version of GMail causes some major style issues 

### ISSUE THREAD

**Issue by nkornaros** [EvHaus/google-redesigned#6]
See the white zones below in the screenshot

![GMAIL](https://user-images.githubusercontent.com/5338599/187221731-18e59905-a73b-4368-908f-7827bb0ba99c.jpg)

Opening a mail also is quite annoying as everything is not readable and icons not visible

**Comment by EvHaus** [comment]
Confirmed. This is happening when you opt-into the "New Gmail" setting. I will add support for it sometime this week.

**Comment by nkornaros** [comment]
> 

Perfect thanks a lot for the quick confirmation and feedback.

**Comment by EvHaus** [comment]
I pushed an update the fixes the most obvious problems, but I still need to make a bunch more tweaks to fix the remaining bits.

**Comment by nkornaros** [comment]
That was fast @EvHaus ! I am using it through Stylus and userStyles.org, do you need to push it there or is there another way for me to use it?
(sorry if it's a stupid question)

**Comment by EvHaus** [comment]
Ok, I think I've fixed the major remaining bits now. I'm going to close this. If there are any other unstyled parts missing, please open a new issue for those.
