### ISSUE TITLE
Event popup title is black over black

### ISSUE THREAD

**Issue by NicolasWebDev** [EvHaus/google-redesigned#66]
Hi @EvHaus , it seems that after a GCal update, once more the title of events on the popup appears as black over black.

![Screenshot from 2024-06-24 09-23-47](https://github.com/EvHaus/google-redesigned/assets/2276631/29115790-247c-4d9c-8bbe-2902c6ca7ae4)

Thanks for the great work!

**Comment by EvHaus** [comment]
Thanks. Fixed in the latest version.
