### ISSUE TITLE
Suggestion: Automatic updates

### ISSUE THREAD

**Issue by ZykeDev** [EvHaus/google-redesigned#9]
I suggest adding an `@updateURL` key to the style heading to allow for automatic updates via Stylish/Stylus clients when the version on the repo changes.
I believe it should point to the raw file on the GitHub servers, so something like this:
`@updateURL      https://raw.githubusercontent.com/EvHaus/google-redesigned/master/css/gmail.css`

Similarly, the `@homepageURL` (linking to this repo) and the `@supportURL` (linking to /issues) keys could also be added if you want to.

**Comment by EvHaus** [comment]
The userstyle right now is distributed and updated through userstyles.org. Do you happen to know what the updateURL should be to continue to use that? I can't find any documentation about how `updateURL` or `homepageURL` works.

**Comment by EvHaus** [comment]
Found the docs at https://github.com/openstyles/stylus/wiki/Writing-UserCSS#usercss-metadata. Will make the change.
